language: ruby

rvm:
  - 2.2.3

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres